import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service",
  description:
    "Terms of Service for My Square Face Icon, a free square face icon generator.",
  alternates: {
    canonical: "/terms-of-service"
  }
};

export default function TermsOfServicePage() {
  return (
    <main className="legal-page">
      <a className="back-link" href="/">Back to Square Face Generator</a>
      <h1>Terms of Service</h1>
      <p>Last updated: May 12, 2026</p>
      <h2>Use of the Tool</h2>
      <p>
        My Square Face Icon provides a free browser-based generator for creating
        simple square avatar images. Use the site responsibly and do not attempt
        to disrupt the service.
      </p>
      <h2>Generated Icons</h2>
      <p>
        You may use icons generated by the first version for personal profile
        images and non-sensitive personal projects. You are responsible for
        checking the rules of any platform where you use the image.
      </p>
      <h2>Comments and Uploads</h2>
      <p>
        Comments and optional uploaded images are moderated before public
        display. Do not submit illegal, abusive, private, copyrighted, or
        impersonating content. We may reject or delete submissions at any time.
      </p>
      <h2>Authorized Game File</h2>
      <p>
        The site is built to run an authorized SWF through Ruffle. Do not extract,
        redistribute, or reuse the game file from this site unless you have your
        own permission to do so.
      </p>
      <h2>No Warranty</h2>
      <p>
        The tool is provided as is. We do not guarantee that every browser,
        device, or download workflow will work without interruption.
      </p>
      <h2>Future Changes</h2>
      <p>
        These terms may be updated as the site adds new features such as asset
        packs, analytics, advertising, or additional pages.
      </p>
    </main>
  );
}
